services:
  - type: web
    name: n8nexperts-api
    runtime: node
    rootDir: api
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
